-- =========================
-- EMAIL EVENTS
-- =========================

CREATE TABLE email_events (
    event_id BIGSERIAL PRIMARY KEY,

    event_type VARCHAR(50) NOT NULL
        CHECK (event_type IN (
            'ACCESS_REQUEST_SUBMITTED',
            'ACCESS_REQUEST_PRIMARY_APPROVAL',
            'ACCESS_REQUEST_PRIMARY_REJECTION',
            'ACCESS_REQUEST_ADMIN_APPROVAL',
            'ACCESS_REQUEST_ADMIN_REJECTION',
            'ROLE_CHANGE_SUBMITTED',
            'ROLE_CHANGE_APPROVED',
            'ROLE_CHANGE_REJECTED',
            'INITIAL_PASSWORD',
            'PASSWORD_RESET'
        ))
);

INSERT INTO email_events (event_type)
VALUES 
('ACCESS_REQUEST_SUBMITTED'),
('ACCESS_REQUEST_PRIMARY_APPROVAL'),
('ACCESS_REQUEST_PRIMARY_REJECTION'),
('ACCESS_REQUEST_ADMIN_APPROVAL'),
('ACCESS_REQUEST_ADMIN_REJECTION'),
('ROLE_CHANGE_SUBMITTED'),
('ROLE_CHANGE_APPROVED'),
('ROLE_CHANGE_REJECTED'),
('INITIAL_PASSWORD'),
('PASSWORD_RESET');
